# Generated by Django 6.0.4 on 2026-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Аталышы')),
                ('description', models.TextField(verbose_name='Толук маалымат')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Сүрөт')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жаңылык',
                'verbose_name_plural': 'Жаңылыктар',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Аты-жөнү')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмети')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Сүрөтү')),
                ('bio', models.TextField(blank=True, verbose_name='Өмүр баяны')),
            ],
            options={
                'verbose_name': 'Мугалим',
                'verbose_name_plural': 'Мугалимдер',
            },
        ),
    ]
