# Generated by Django 6.0.4 on 2026-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Альбомдун аты')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Класс')),
                ('file', models.FileField(upload_to='schedules/', verbose_name='Расписание (PDF же Сүрөт)')),
            ],
            options={
                'verbose_name': 'Сабак графиги',
                'verbose_name_plural': 'Сабак графиктери',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Толук маалымат'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Толук маалымат'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Толук маалымат'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Аталышы'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Аталышы'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Аталышы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Өмүр баяны'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Өмүр баяны'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Өмүр баяны'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Аты-жөнү'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Аты-жөнү'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Аты-жөнү'),
        ),
    ]
