# Generated by Django 6.0.4 on 2026-04-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_gallery_schedule_news_description_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жетишкендик')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Жетишкендик')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Жетишкендик')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Жетишкендик')),
                ('description', models.TextField(verbose_name='Кыскача маалымат')),
                ('description_ky', models.TextField(null=True, verbose_name='Кыскача маалымат')),
                ('description_ru', models.TextField(null=True, verbose_name='Кыскача маалымат')),
                ('description_tr', models.TextField(null=True, verbose_name='Кыскача маалымат')),
                ('image', models.ImageField(upload_to='achievements/', verbose_name='Сүрөт/Диплом')),
            ],
            options={
                'verbose_name': 'Жетишкендик',
                'verbose_name_plural': 'Жетишкендиктер',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Сүрөттүн аталышы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='file',
            field=models.FileField(upload_to='schedules/', verbose_name='Расписание'),
        ),
    ]
