# Generated by Django 6.0.4 on 2026-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_achievement_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='file',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Аякташы'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Башталышы'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Мугалим'),
        ),
    ]
